moderation: Drop unused ReviewItem code
Dropped since 444634c8fc8439563534cd2e68a8c8734d6a4489

Fixes clippy lint

```
error: struct `ReviewItem` is never constructed
  --> src/review/moderation.rs:18:12
   |
18 | pub struct ReviewItem {
   |            ^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`

error: could not compile `flathub-hooks` (bin "flathub-hooks") due to 1 previous error
```